library(haven)

valid<-read_sas("M:/xstudy2/Simulation/aim02/July2017/valid.sas7bdat")
valid<-valid[,c("ID","GEN1A001","COL1Z007")]
names(valid)<-c("ID","gender","frat")

c1l0<-c("p45n25d0c1l0","p45n25d1c1l0","p25n25d0c1l0","p25n25d1c1l0","p45n50d0c1l0","p45n50d1c1l0","p25n50d0c1l0","p25n50d1c1l0","p45n100d0c1l0","p45n100d1c1l0","p25n100d0c1l0","p25n100d1c1l0")
c1l1<-c("p45n25d0c1l1","p45n25d1c1l1","p25n25d0c1l1","p25n25d1c1l1","p45n50d0c1l1","p45n50d1c1l1","p25n50d0c1l1","p25n50d1c1l1","p45n100d0c1l1","p45n100d1c1l1","p25n100d0c1l1","p25n100d1c1l1")
c2l0<-c("p45n25d0c2l0","p45n25d1c2l0","p25n25d0c2l0","p25n25d1c2l0","p45n50d0c2l0","p45n50d1c2l0","p25n50d0c2l0","p25n50d1c2l0","p45n100d0c2l0","p45n100d1c2l0","p25n100d0c2l0","p25n100d1c2l0")
c2l1<-c("p45n25d0c2l1","p45n25d1c2l1","p25n25d0c2l1","p25n25d1c2l1","p45n50d0c2l1","p45n50d1c2l1","p25n50d0c2l1","p25n50d1c2l1","p45n100d0c2l1","p45n100d1c2l1","p25n100d0c2l1","p25n100d1c2l1")
all.sets<-list(c1l0,c1l1,c2l0,c2l1)

#runModels("C:/Users/vcole/Desktop/aim2/p45n50d0c1l0")
#runModels("C:/Users/vcole/Desktop/aim2/p45n50d0c1l1")
#runModels("C:/Users/vcole/Desktop/aim2/p45n50d1c1l0")
#runModels("C:/Users/vcole/Desktop/aim2/p45n50d1c1l1")
#runModels("C:/Users/vcole/Desktop/aim2/p45n50d0c2l0")
#runModels("C:/Users/vcole/Desktop/aim2/p45n50d0c2l1")
#runModels("C:/Users/vcole/Desktop/aim2/p45n50d1c2l0")
#runModels("C:/Users/vcole/Desktop/aim2/p45n50d1c2l1")

names.c1l0<-c('ACY2','ACY3','ACY4','ACY6','ACY12','ACY14')
names.c1l1<-c('ACY1','ACY2','ACY3','ACY4','ACY5','ACY6','ACY7','ACY8','ACY9','ACY10','ACY12','ACY13','ACY14','ACY15','ACY18')
names.c2l0<-c('AMT10','AMT11','AMT12','AMT14','AMT16','AMT18')
names.c2l1<-c('AMT8','AMT9','AMT10','AMT11','AMT12','AMT13','AMT14','AMT15','AMT16','AMT17','AMT18')

all.names<-list(names.c1l0,names.c1l1,names.c2l0,names.c2l1)
full.names<-list(names.c1l1,names.c1l1,names.c2l1,names.c2l1)


# Model Specifications ----------------------------------------------------


#Alcohol consequences, intercept only, short form
model.io.acy.l0<-paste('Model:',
                       '%OVERALL%',
                       '[ACY2$1];',
                       '[ACY3$1];',
                       '[ACY4$1];',
                       '[ACY6$1];',
                       '[ACY12$1];',
                       '[ACY14$1];',
                       '%C#1%',
                       '[ACY2$1] (a2);',
                       '[ACY3$1] (a3);',
                       '[ACY4$1] (a4);',
                       '[ACY6$1] (a6);',
                       '[ACY12$1] (a12);',
                       '[ACY14$1] (a14);',
                       '%C#2%',
                       '[ACY2$1] (b2);',
                       '[ACY3$1] (b3);',
                       '[ACY4$1] (b4);',
                       '[ACY6$1] (b6);',
                       '[ACY12$1] (b12);',
                       '[ACY14$1] (b14);',
                       '%C#3%',
                       '[ACY2$1] (a2);',
                       '[ACY3$1] (a3);',
                       '[ACY4$1] (a4);',
                       '[ACY6$1] (a6);',
                       '[ACY12$1] (a12);',
                       '[ACY14$1] (a14);',
                       '%C#4%',
                       '[ACY2$1] (b2);',
                       '[ACY3$1] (b3);',
                       '[ACY4$1] (b4);',
                       '[ACY6$1] (b6);',
                       '[ACY12$1] (b12);',
                       '[ACY14$1] (b14);',
                       sep="\n")


#Alcohol consequences, intercept only, short form
model.ud.acy.l0<-paste('Model:',
                       '%OVERALL%',
                       '[ACY2$1];',
                       '[ACY3$1];',
                       '[ACY4$1];',
                       '[ACY6$1];',
                       '[ACY12$1];',
                       '[ACY14$1];',
                       '%C#1%',
                       '[ACY2$1] (a2);',
                       '[ACY3$1] (a3);',
                       '[ACY4$1] (a4);',
                       '[ACY6$1] (a6);',
                       '[ACY12$1] (a12);',
                       '[ACY14$1] (a14);',
                       '%C#2%',
                       '[ACY2$1] (b2);',
                       '[ACY3$1] (b3);',
                       '[ACY4$1] (b4);',
                       '[ACY6$1] (b6);',
                       '[ACY12$1] (b12);',
                       '[ACY14$1] (b14);',
                       '%C#3%',
                       '[ACY2$1] (a2);',
                       '[ACY3$1] ;',
                       '[ACY4$1] ;',
                       '[ACY6$1] (a6);',
                       '[ACY12$1] ;',
                       '[ACY14$1] (a14);',
                       '%C#4%',
                       '[ACY2$1] (b2);',
                       '[ACY3$1] ;',
                       '[ACY4$1] ;',
                       '[ACY6$1] (b6);',
                       '[ACY12$1] ;',
                       '[ACY14$1] (b14);',
                       sep="\n")

#Alcohol consequences, uniform DIF, long form
model.ud.acy.l1<-paste('Model:',
                       '%OVERALL%',
                       '[ACY1$1];',
                       '[ACY2$1];',
                       '[ACY3$1];',
                       '[ACY4$1];',
                       '[ACY5$1];',
                       '[ACY6$1];',
                       '[ACY7$1];',
                       '[ACY8$1];',
                       '[ACY9$1];',
                       '[ACY10$1];',
                       '[ACY12$1];',
                       '[ACY13$1];',
                       '[ACY14$1];',
                       '[ACY15$1];',
                       '[ACY18$1];',
                       '%C#1%',
                       '[ACY1$1] (a1);',
                       '[ACY2$1] (a2);',
                       '[ACY3$1] (a3);',
                       '[ACY4$1] (a4);',
                       '[ACY5$1] (a5);',
                       '[ACY6$1] (a6);',
                       '[ACY7$1] (a7);',
                       '[ACY8$1] (a8);',
                       '[ACY9$1] (a9);',
                       '[ACY10$1] (a10);',
                       '[ACY12$1] (a12);',
                       '[ACY13$1] (a13);',
                       '[ACY14$1] (a14);',
                       '[ACY15$1] (a15);',
                       '[ACY18$1] (a18);',
                       '%C#2%',
                       '[ACY1$1] (b1);',
                       '[ACY2$1] (b2);',
                       '[ACY3$1] (b3);',
                       '[ACY4$1] (b4);',
                       '[ACY5$1] (b5);',
                       '[ACY6$1] (b6);',
                       '[ACY7$1] (b7);',
                       '[ACY8$1] (b8);',
                       '[ACY9$1] (b9);',
                       '[ACY10$1] (b10);',
                       '[ACY12$1] (b12);',
                       '[ACY13$1] (b13);',
                       '[ACY14$1] (b14);',
                       '[ACY15$1] (b15);',
                       '[ACY18$1] (b18);',
                       '%C#3%',
                       '[ACY1$1] (a1);',
                       '[ACY2$1] (a2);',
                       '[ACY3$1];',
                       '[ACY4$1];',
                       '[ACY5$1] (a5);',
                       '[ACY6$1] (a6);',
                       '[ACY7$1] (a7);',
                       '[ACY8$1] (a8);',
                       '[ACY9$1] (a9);',
                       '[ACY10$1] (a10);',
                       '[ACY12$1];',
                       '[ACY13$1] (a13);',
                       '[ACY14$1] (a14);',
                       '[ACY15$1] (a15);',
                       '[ACY18$1] (a18);',
                       '%C#4%',
                       '[ACY1$1] (b1);',
                       '[ACY2$1] (b2);',
                       '[ACY3$1]; ',
                       '[ACY4$1]; ',
                       '[ACY5$1] (b5);',
                       '[ACY6$1] (b6);',
                       '[ACY7$1] (b7);',
                       '[ACY8$1] (b8);',
                       '[ACY9$1] (b9);',
                       '[ACY10$1] (b10);',
                       '[ACY12$1]; ',
                       '[ACY13$1] (b13);',
                       '[ACY14$1] (b14);',
                       '[ACY15$1] (b15);',
                       '[ACY18$1] (b18);',
                       sep="\n")

#Alcohol consequences, intercept only, long form
model.io.acy.l1<-paste('Model:',
                       '%OVERALL%',
                       '[ACY1$1];',
                       '[ACY2$1];',
                       '[ACY3$1];',
                       '[ACY4$1];',
                       '[ACY5$1];',
                       '[ACY6$1];',
                       '[ACY7$1];',
                       '[ACY8$1];',
                       '[ACY9$1];',
                       '[ACY10$1];',
                       '[ACY12$1];',
                       '[ACY13$1];',
                       '[ACY14$1];',
                       '[ACY15$1];',
                       '[ACY18$1];',
                       '%C#1%',
                       '[ACY1$1] (a1);',
                       '[ACY2$1] (a2);',
                       '[ACY3$1] (a3);',
                       '[ACY4$1] (a4);',
                       '[ACY5$1] (a5);',
                       '[ACY6$1] (a6);',
                       '[ACY7$1] (a7);',
                       '[ACY8$1] (a8);',
                       '[ACY9$1] (a9);',
                       '[ACY10$1] (a10);',
                       '[ACY12$1] (a12);',
                       '[ACY13$1] (a13);',
                       '[ACY14$1] (a14);',
                       '[ACY15$1] (a15);',
                       '[ACY18$1] (a18);',
                       '%C#2%',
                       '[ACY1$1] (b1);',
                       '[ACY2$1] (b2);',
                       '[ACY3$1] (b3);',
                       '[ACY4$1] (b4);',
                       '[ACY5$1] (b5);',
                       '[ACY6$1] (b6);',
                       '[ACY7$1] (b7);',
                       '[ACY8$1] (b8);',
                       '[ACY9$1] (b9);',
                       '[ACY10$1] (b10);',
                       '[ACY12$1] (b12);',
                       '[ACY13$1] (b13);',
                       '[ACY14$1] (b14);',
                       '[ACY15$1] (b15);',
                       '[ACY18$1] (b18);',
                       '%C#3%',
                       '[ACY1$1] (a1);',
                       '[ACY2$1] (a2);',
                       '[ACY3$1] (a3);',
                       '[ACY4$1] (a4);',
                       '[ACY5$1] (a5);',
                       '[ACY6$1] (a6);',
                       '[ACY7$1] (a7);',
                       '[ACY8$1] (a8);',
                       '[ACY9$1] (a9);',
                       '[ACY10$1] (a10);',
                       '[ACY12$1] (a12);',
                       '[ACY13$1] (a13);',
                       '[ACY14$1] (a14);',
                       '[ACY15$1] (a15);',
                       '[ACY18$1] (a18);',
                       '%C#4%',
                       '[ACY1$1] (b1);',
                       '[ACY2$1] (b2);',
                       '[ACY3$1]; (b3)',
                       '[ACY4$1]; (b4)',
                       '[ACY5$1] (b5);',
                       '[ACY6$1] (b6);',
                       '[ACY7$1] (b7);',
                       '[ACY8$1] (b8);',
                       '[ACY9$1] (b9);',
                       '[ACY10$1] (b10);',
                       '[ACY12$1] (b12); ',
                       '[ACY13$1] (b13);',
                       '[ACY14$1] (b14);',
                       '[ACY15$1] (b15);',
                       '[ACY18$1] (b18);',
                       sep="\n")

####MOTIVES
#Alcohol motives, short form, uniform DIF
model.ud.amt.l0<-paste("Model:",
                       "%OVERALL%",
                       "%C#1%",
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1] (a121);',
                       '[AMT12$2] (a122);',
                       '[AMT12$3] (a123);',
                       '[AMT12$4] (a124);',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#2%',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1] (b121);',
                       '[AMT12$2] (b122);',
                       '[AMT12$3] (b123);',
                       '[AMT12$4] (b124);',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);',
                       '%C#3%',
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1];',
                       '[AMT12$2];',
                       '[AMT12$3];',
                       '[AMT12$4];',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#4%',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1];',
                       '[AMT12$2];',
                       '[AMT12$3];',
                       '[AMT12$4];',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);',
                       sep="\n")

#Alcohol motives, short form, intercept only
model.io.amt.l0<-paste('Model:',
                       '%OVERALL%',
                       '%C#1%',
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1] (a121);',
                       '[AMT12$2] (a122);',
                       '[AMT12$3] (a123);',
                       '[AMT12$4] (a124);',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#2%',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1] (b121);',
                       '[AMT12$2] (b122);',
                       '[AMT12$3] (b123);',
                       '[AMT12$4] (b124);',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);',
                       '%C#3%',
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1] (a121);',
                       '[AMT12$2] (a122);',
                       '[AMT12$3] (a123);',
                       '[AMT12$4] (a124);',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#4%',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1] (b121);',
                       '[AMT12$2] (b122);',
                       '[AMT12$3] (b123);',
                       '[AMT12$4] (b124);',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);'
                       ,sep="\n")

#Alcohol motives, long form, uniform DIF
model.ud.amt.l1<-paste("Model:",
                       "%OVERALL%",
                       "%C#1%",
                       '[AMT8$1] (a81);',
                       '[AMT8$2] (a82);',
                       '[AMT8$3] (a83);',
                       '[AMT8$4] (a84);',
                       '[AMT9$1] (a91);',
                       '[AMT9$2] (a92);',
                       '[AMT9$3] (a93);',
                       '[AMT9$4] (a94);',
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1] (a121);',
                       '[AMT12$2] (a122);',
                       '[AMT12$3] (a123);',
                       '[AMT12$4] (a124);',
                       '[AMT13$1] (a131);',
                       '[AMT13$2] (a132);',
                       '[AMT13$3] (a133);',
                       '[AMT13$4] (a134);',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT15$1] (a151);',
                       '[AMT15$2] (a152);',
                       '[AMT15$3] (a153);',
                       '[AMT15$4] (a154);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT17$1] (a171);',
                       '[AMT17$2] (a172);',
                       '[AMT17$3] (a173);',
                       '[AMT17$4] (a174);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#2%',
                       '[AMT8$1] (b81);',
                       '[AMT8$2] (b82);',
                       '[AMT8$3] (b83);',
                       '[AMT8$4] (b84);',
                       '[AMT9$1] (b91);',
                       '[AMT9$2] (b92);',
                       '[AMT9$3] (b93);',
                       '[AMT9$4] (b94);',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1] (b121);',
                       '[AMT12$2] (b122);',
                       '[AMT12$3] (b123);',
                       '[AMT12$4] (b124);',
                       '[AMT13$1] (b131);',
                       '[AMT13$2] (b132);',
                       '[AMT13$3] (b133);',
                       '[AMT13$4] (b134);',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT15$1] (b151);',
                       '[AMT15$2] (b152);',
                       '[AMT15$3] (b153);',
                       '[AMT15$4] (b154);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT17$1] (b171);',
                       '[AMT17$2] (b172);',
                       '[AMT17$3] (b173);',
                       '[AMT17$4] (b174);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);',
                       '%C#3%',
                       '[AMT8$1] (a81);',
                       '[AMT8$2] (a82);',
                       '[AMT8$3] (a83);',
                       '[AMT8$4] (a84);',
                       '[AMT9$1] (a91);',
                       '[AMT9$2] (a92);',
                       '[AMT9$3] (a93);',
                       '[AMT9$4] (a94);',
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1] ;',
                       '[AMT12$2] ;',
                       '[AMT12$3] ;',
                       '[AMT12$4] ;',
                       '[AMT13$1] (a131);',
                       '[AMT13$2] (a132);',
                       '[AMT13$3] (a133);',
                       '[AMT13$4] (a134);',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT15$1] (a151);',
                       '[AMT15$2] (a152);',
                       '[AMT15$3] (a153);',
                       '[AMT15$4] (a154);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT17$1] (a171);',
                       '[AMT17$2] (a172);',
                       '[AMT17$3] (a173);',
                       '[AMT17$4] (a174);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#4%',
                       '[AMT8$1] (b81);',
                       '[AMT8$2] (b82);',
                       '[AMT8$3] (b83);',
                       '[AMT8$4] (b84);',
                       '[AMT9$1] (b91);',
                       '[AMT9$2] (b92);',
                       '[AMT9$3] (b93);',
                       '[AMT9$4] (b94);',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1] ;',
                       '[AMT12$2] ;',
                       '[AMT12$3] ;',
                       '[AMT12$4] ;',
                       '[AMT13$1] (b131);',
                       '[AMT13$2] (b132);',
                       '[AMT13$3] (b133);',
                       '[AMT13$4] (b134);',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT15$1] (b151);',
                       '[AMT15$2] (b152);',
                       '[AMT15$3] (b153);',
                       '[AMT15$4] (b154);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT17$1] (b171);',
                       '[AMT17$2] (b172);',
                       '[AMT17$3] (b173);',
                       '[AMT17$4] (b174);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);',
                       sep="\n")


#Alcohol motives, long form, intercept only
model.io.amt.l1<-paste("Model:",
                       "%OVERALL%",
                       "%C#1%",
                       '[AMT8$1] (a81);',
                       '[AMT8$2] (a82);',
                       '[AMT8$3] (a83);',
                       '[AMT8$4] (a84);',
                       '[AMT9$1] (a91);',
                       '[AMT9$2] (a92);',
                       '[AMT9$3] (a93);',
                       '[AMT9$4] (a94);',
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1] (a121);',
                       '[AMT12$2] (a122);',
                       '[AMT12$3] (a123);',
                       '[AMT12$4] (a124);',
                       '[AMT13$1] (a131);',
                       '[AMT13$2] (a132);',
                       '[AMT13$3] (a133);',
                       '[AMT13$4] (a134);',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT15$1] (a151);',
                       '[AMT15$2] (a152);',
                       '[AMT15$3] (a153);',
                       '[AMT15$4] (a154);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT17$1] (a171);',
                       '[AMT17$2] (a172);',
                       '[AMT17$3] (a173);',
                       '[AMT17$4] (a174);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#2%',
                       '[AMT8$1] (b81);',
                       '[AMT8$2] (b82);',
                       '[AMT8$3] (b83);',
                       '[AMT8$4] (b84);',
                       '[AMT9$1] (b91);',
                       '[AMT9$2] (b92);',
                       '[AMT9$3] (b93);',
                       '[AMT9$4] (b94);',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1] (b121);',
                       '[AMT12$2] (b122);',
                       '[AMT12$3] (b123);',
                       '[AMT12$4] (b124);',
                       '[AMT13$1] (b131);',
                       '[AMT13$2] (b132);',
                       '[AMT13$3] (b133);',
                       '[AMT13$4] (b134);',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT15$1] (b151);',
                       '[AMT15$2] (b152);',
                       '[AMT15$3] (b153);',
                       '[AMT15$4] (b154);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT17$1] (b171);',
                       '[AMT17$2] (b172);',
                       '[AMT17$3] (b173);',
                       '[AMT17$4] (b174);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);',
                       '%C#3%',
                       '[AMT8$1] (a81);',
                       '[AMT8$2] (a82);',
                       '[AMT8$3] (a83);',
                       '[AMT8$4] (a84);',
                       '[AMT9$1] (a91);',
                       '[AMT9$2] (a92);',
                       '[AMT9$3] (a93);',
                       '[AMT9$4] (a94);',
                       '[AMT10$1] (a101);',
                       '[AMT10$2] (a102);',
                       '[AMT10$3] (a103);',
                       '[AMT10$4] (a104);',
                       '[AMT11$1] (a111);',
                       '[AMT11$2] (a112);',
                       '[AMT11$3] (a113);',
                       '[AMT11$4] (a114);',
                       '[AMT12$1] (a121);',
                       '[AMT12$2] (a122);',
                       '[AMT12$3] (a123);',
                       '[AMT12$4] (a124);',
                       '[AMT13$1] (a131);',
                       '[AMT13$2] (a132);',
                       '[AMT13$3] (a133);',
                       '[AMT13$4] (a134);',
                       '[AMT14$1] (a141);',
                       '[AMT14$2] (a142);',
                       '[AMT14$3] (a143);',
                       '[AMT14$4] (a144);',
                       '[AMT15$1] (a151);',
                       '[AMT15$2] (a152);',
                       '[AMT15$3] (a153);',
                       '[AMT15$4] (a154);',
                       '[AMT16$1] (a161);',
                       '[AMT16$2] (a162);',
                       '[AMT16$3] (a163);',
                       '[AMT16$4] (a164);',
                       '[AMT17$1] (a171);',
                       '[AMT17$2] (a172);',
                       '[AMT17$3] (a173);',
                       '[AMT17$4] (a174);',
                       '[AMT18$1] (a181);',
                       '[AMT18$2] (a182);',
                       '[AMT18$3] (a183);',
                       '[AMT18$4] (a184);',
                       '%C#4%',
                       '[AMT8$1] (b81);',
                       '[AMT8$2] (b82);',
                       '[AMT8$3] (b83);',
                       '[AMT8$4] (b84);',
                       '[AMT9$1] (b91);',
                       '[AMT9$2] (b92);',
                       '[AMT9$3] (b93);',
                       '[AMT9$4] (b94);',
                       '[AMT10$1] (b101);',
                       '[AMT10$2] (b102);',
                       '[AMT10$3] (b103);',
                       '[AMT10$4] (b104);',
                       '[AMT11$1] (b111);',
                       '[AMT11$2] (b112);',
                       '[AMT11$3] (b113);',
                       '[AMT11$4] (b114);',
                       '[AMT12$1] (b121);',
                       '[AMT12$2] (b122);',
                       '[AMT12$3] (b123);',
                       '[AMT12$4] (b124);',
                       '[AMT13$1] (b131);',
                       '[AMT13$2] (b132);',
                       '[AMT13$3] (b133);',
                       '[AMT13$4] (b134);',
                       '[AMT14$1] (b141);',
                       '[AMT14$2] (b142);',
                       '[AMT14$3] (b143);',
                       '[AMT14$4] (b144);',
                       '[AMT15$1] (b151);',
                       '[AMT15$2] (b152);',
                       '[AMT15$3] (b153);',
                       '[AMT15$4] (b154);',
                       '[AMT16$1] (b161);',
                       '[AMT16$2] (b162);',
                       '[AMT16$3] (b163);',
                       '[AMT16$4] (b164);',
                       '[AMT17$1] (b171);',
                       '[AMT17$2] (b172);',
                       '[AMT17$3] (b173);',
                       '[AMT17$4] (b174);',
                       '[AMT18$1] (b181);',
                       '[AMT18$2] (b182);',
                       '[AMT18$3] (b183);',
                       '[AMT18$4] (b184);',
                       sep="\n")



models.io<-list(model.io.acy.l0,model.io.acy.l1,model.io.amt.l0,model.io.amt.l1)
models.ud<-list(model.ud.acy.l0,model.ud.acy.l1,model.ud.amt.l0,model.ud.amt.l1)

library(MplusAutomation)

# Main iterative model fitting function -----------------------------------
for (i in 1:4) {
  for (j in 1:12) {
    for (r in 1:100) {
      the.filename<-paste0("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"R",r,".csv")
      if (file.exists(the.filename)==1) {
        indata<-read.csv(the.filename,header=FALSE) #Read in one of the data files, as currently formatted for Mplus
        names(indata)<-c("Dx","ID",full.names[[i]],"NumberHits","study","R","T1original","T2original")
        
        ###Training data
        ###Note that T1original and T2original are the corresponding training values in the MIMIC solution
        indata$T1<-0
        indata$T2<-0
        indata$T3<-0
        indata$T4<-0
        
        #Study 1, diagnosed. If you are in Study 1 and have AUD, you can only be a member of class 1, so T1=1, T2=0, T3=0, T4=0.
        indata$T1[indata$study==1&indata$Dx==1]<-1
        #Study 1, undiagnosed. If you are in Study 1 and do not have AUD, you can only be a member of class 2, so T1=0, T2=1, T3=0, T4=0.
        indata$T2[indata$study==1&indata$Dx==0]<-1
        #Study 2, diagnosed or undiagnosed. You can be in class 3, is diagnosed for Study 2, or class 4, which is undiagnosed for Study 2. So T1=0, T2=0, T3=1, and T4=1. 
        indata$T3[indata$study==2]<-1
        indata$T4[indata$study==2]<-1
        
        
#         gender.p<-c(0.4285714, 0.4871795)
#         frat.p<-c(0.1889401, 0.3128205)
#         
#         indata$gender<-NA
#         indata$frat<-NA
#         for (a in 1:nrow(indata)) {
#           if (indata$Dx[a]==0) {
#             indata$gender[a]<-rbinom(1,1,gender.p[1])
#             indata$frat[a]<-rbinom(1,1,frat.p[1])
#           }
#           if (indata$Dx[a]==1) {
#             indata$gender[a]<-rbinom(1,1,gender.p[2])
#             indata$frat[a]<-rbinom(1,1,frat.p[2])
#           }
#         }
        
        indata<-merge(indata,valid,by="ID")

        write.table(indata,paste0("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_r",r,"_mg.csv"),sep=",",row.names=FALSE,col.names=FALSE,na=".")
        
        the.datafile.original<-paste0(all.sets[[i]][j],"_r",r,"_mg.csv")
        the.datafile.io.3step<-paste0(all.sets[[i]][j],"_r",r,"_io_v.dat")
        the.datafile.ud.3step<-paste0(all.sets[[i]][j],"_r",r,"_ud_v.dat")
        
        the.io.text<-paste(
          "TITLE:  Test run to get D matrix;",
          "DATA:  FILE IS",paste0(the.datafile.original,";"),
          "FORMAT=FREE;",
          "VARIABLE: NAMES ARE",
          paste(names(indata),collapse="\n    "),
          ";",
          "    USEVARIABLES =",
          paste(all.names[[i]],collapse="\n    "),
          "T1 T2 T3 T4;",
          "    CATEGORICAL =",
          paste(all.names[[i]],collapse="\n    "),
          ";",
          "    AUXILIARY ARE GENDER FRAT DX;",
          "    CLASSES = C(4);",
          "    TRAINING = T1 T2 T3 T4;",
          "    MISSING are all .;",
          "    IDVARIABLE = ID;",
          "ANALYSIS:",
          "    TYPE = MIXTURE;",
          "    PROCESS = 4;",
          models.io[[i]],
          "SAVEDATA:",
          "SAVE = CPROB;",
          "FILE =", the.datafile.io.3step,
          sep="\n")  
        
        the.io.name<-paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_io_r",r,".inp",sep="")
        the.io<-file(the.io.name)
        writeLines(the.io.text, the.io)
        close(the.io)
        #runModels(the.io.name,replaceOutfile="never")
        
        the.ud.text<-paste(
          "TITLE:  Test run to get D matrix;",
          "DATA:  FILE IS",paste0(the.datafile.original,";"),
          "FORMAT=FREE;",
          "VARIABLE: NAMES ARE",
          paste(names(indata),collapse="\n    "),
          ";",
          "    USEVARIABLES =",
          paste(all.names[[i]],collapse="\n    "),
          "T1 T2 T3 T4;",
          "    CATEGORICAL =",
          paste(all.names[[i]],collapse="\n    "),
          ";",
          "    AUXILIARY ARE GENDER FRAT DX;",
          "    CLASSES = C(4);",
          "    TRAINING = T1 T2 T3 T4;",
          "    MISSING are all .;",
          "    IDVARIABLE = ID;",
          "ANALYSIS:",
          "    TYPE = MIXTURE;",
          "    PROCESS = 4;",
          models.ud[[i]],
          "SAVEDATA:",
          "SAVE = CPROB;",
          "FILE =", the.datafile.ud.3step,
          sep="\n")  
        
        the.ud.name<-paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_ud_r",r,".inp",sep="")
        the.ud<-file(the.ud.name)
        writeLines(the.ud.text, the.ud)
        close(the.ud)
        #runModels(the.ud.name,replaceOutfile="never")
        
      }
    }
  }
}

#####
for (i in 1:4) {
  for (j in 1:12) {
    for (r in 1:100) {
      the.ud.out<-paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_io_r",r,".out",sep="")
      if (file.exists(the.ud.out)==TRUE) {
        
        #Have to truncate these for Mplus
        the.datafile.ud<-paste(all.sets[[i]][j],"_r",r,"_ud_v.dat",sep="")
        the.datafile.io<-paste(all.sets[[i]][j],"_r",r,"_io_v.dat",sep="")
        
        qlogit_ud<-MplusAutomation::readModels(paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_ud_r",r,".out",sep=""))$class_counts$logitProbs.mostLikely
        qlogit_io<-MplusAutomation::readModels(paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_io_r",r,".out",sep=""))$class_counts$logitProbs.mostLikely
        
        the.l33_ud<-paste0("   [N#3@",qlogit_ud[3,3],"];")
        the.l43_ud<-paste0("   [N#3@",qlogit_ud[4,3],"];")
        
        the.l33_io<-paste0("   [N#3@",qlogit_io[3,3],"];")
        the.l43_io<-paste0("   [N#3@",qlogit_io[4,3],"];")
        
        the.ud.text.v.gender<-paste(
          "TITLE:  Test run to get D matrix;",
          "DATA:  FILE IS",paste0(the.datafile.ud,";"),
          "FORMAT=FREE;",
          "VARIABLE:",
          "NAMES ARE",
          paste(all.names[[i]],collapse="\n    "),
          "    T1 T2 T3 T4 ID GENDER FRAT DX",
          "    CPROB1 CPROB2 CPROB3 CPROB4 N;",
          "    USEVARIABLES ARE N GENDER;",
          "    NOMINAL = N;",
          "    CLASSES = C(4);",
          "    MISSING are all *;",
          "    IDVARIABLE = ID;",
          "ANALYSIS:",
          "    TYPE = MIXTURE;",
          "    STARTS = 0;",
          "MODEL:",
          "    %OVERALL%",
          "    c ON gender;",
          "    %C#1%",
          "    [N#1@15];",
          "    [N#2@-15];",
          "    [N#3@-15];",
          "    %C#2%",
          "    [N#1@-15];",
          "    [N#2@15];",
          "    [N#3@-15];",
          "    %C#3%",
          "    [N#1@-15];",
          "    [N#2@-15];",
          the.l33_ud,
          "    %C#4%",
          "    [N#1@-15];",
          "    [N#2@-15];",
          the.l43_ud,
          "OUTPUT:",
          "   TECH3",
          "SAVEDATA:",
          "TECH3 = t3vg_", the.datafile.ud.3step,
          sep="\n")  
        
        the.ud.name.v.gender<-paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_ud_r",r,"_v_gender.inp",sep="")
        the.ud.input.v.gender<-file(the.ud.name.v.gender)
        writeLines(the.ud.text.v.gender, the.ud.input.v.gender)
        close(the.ud.input.v.gender)
        runModels(the.ud.name.v.gender,replaceOutfile="never")
        
        
        the.ud.text.v.frat<-paste(
          "TITLE:  Test run to get D matrix;",
          "DATA:  FILE IS",paste0(the.datafile.ud,";"),
          "FORMAT=FREE;",
          "VARIABLE:",
          "NAMES ARE",
          paste(all.names[[i]],collapse="\n    "),
          "    T1 T2 T3 T4 ID GENDER FRAT DX",
          "    CPROB1 CPROB2 CPROB3 CPROB4 N;",
          "    USEVARIABLES ARE N FRAT;",
          "    NOMINAL = N;",
          "    CLASSES = C(4);",
          "    MISSING are all *;",
          "    IDVARIABLE = ID;",
          "ANALYSIS:",
          "    TYPE = MIXTURE;",
          "    STARTS = 0;",
          "MODEL:",
          "    %OVERALL%",
          "    c ON frat;",
          "    %C#1%",
          "    [N#1@15];",
          "    [N#2@-15];",
          "    [N#3@-15];",
          "    %C#2%",
          "    [N#1@-15];",
          "    [N#2@15];",
          "    [N#3@-15];",
          "    %C#3%",
          "    [N#1@-15];",
          "    [N#2@-15];",
          the.l33_ud,
          "    %C#4%",
          "    [N#1@-15];",
          "    [N#2@-15];",
          the.l43_ud,
          "OUTPUT:",
          "   TECH3",
          "SAVEDATA:",
          "TECH3 = t3vf_", the.datafile.ud.3step,
          sep="\n")  
        
        the.ud.name.v.frat<-paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_ud_r",r,"_v_frat.inp",sep="")
        the.ud.input.v.frat<-file(the.ud.name.v.frat)
        writeLines(the.ud.text.v.frat, the.ud.input.v.frat)
        close(the.ud.input.v.frat)
        runModels(the.ud.name.v.frat,replaceOutfile="never")
        
      
        
      
      the.io.text.v.gender<-paste(
        "TITLE:  Test run to get D matrix;",
        "DATA:  FILE IS",paste0(the.datafile.io,";"),
        "FORMAT=FREE;",
        "VARIABLE:",
        "NAMES ARE",
        paste(all.names[[i]],collapse="\n    "),
        "    T1 T2 T3 T4 ID GENDER FRAT DX",
        "    CPROB1 CPROB2 CPROB3 CPROB4 N;",
        "    USEVARIABLES ARE N GENDER;",
        "    NOMINAL = N;",
        "    CLASSES = C(4);",
        "    MISSING are all *;",
        "    IDVARIABLE = ID;",
        "ANALYSIS:",
        "    TYPE = MIXTURE;",
        "    STARTS = 0;",
        "MODEL:",
        "    %OVERALL%",
        "    c ON gender;",
        "    %C#1%",
        "    [N#1@15];",
        "    [N#2@-15];",
        "    [N#3@-15];",
        "    %C#2%",
        "    [N#1@-15];",
        "    [N#2@15];",
        "    [N#3@-15];",
        "    %C#3%",
        "    [N#1@-15];",
        "    [N#2@-15];",
        the.l33_ud,
        "    %C#4%",
        "    [N#1@-15];",
        "    [N#2@-15];",
        the.l43_ud,
        "OUTPUT:",
        "   TECH3",
        "SAVEDATA:",
        "TECH3 = t3vg_", the.datafile.io.3step,
        sep="\n")  
      
      the.io.name.v.gender<-paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_io_r",r,"_v_gender.inp",sep="")
      the.io.input.v.gender<-file(the.io.name.v.gender)
      writeLines(the.io.text.v.gender, the.io.input.v.gender)
      close(the.io.input.v.gender)
      runModels(the.io.name.v.gender,replaceOutfile="never")
      
      
      
      
      the.io.text.v.frat<-paste(
        "TITLE:  Test run to get D matrix;",
        "DATA:  FILE IS",paste0(the.datafile.io,";"),
        "FORMAT=FREE;",
        "VARIABLE:",
        "NAMES ARE",
        paste(all.names[[i]],collapse="\n    "),
        "    T1 T2 T3 T4 ID GENDER FRAT DX",
        "    CPROB1 CPROB2 CPROB3 CPROB4 N;",
        "    USEVARIABLES ARE N FRAT;",
        "    NOMINAL = N;",
        "    CLASSES = C(4);",
        "    MISSING are all *;",
        "    IDVARIABLE = ID;",
        "ANALYSIS:",
        "    TYPE = MIXTURE;",
        "    STARTS = 0;",
        "MODEL:",
        "    %OVERALL%",
        "    c ON frat;",
        "    %C#1%",
        "    [N#1@15];",
        "    [N#2@-15];",
        "    [N#3@-15];",
        "    %C#2%",
        "    [N#1@-15];",
        "    [N#2@15];",
        "    [N#3@-15];",
        "    %C#3%",
        "    [N#1@-15];",
        "    [N#2@-15];",
        the.l33_io,
        "    %C#4%",
        "    [N#1@-15];",
        "    [N#2@-15];",
        the.l43_io,
        "OUTPUT:",
        "   TECH3",
        "SAVEDATA:",
        "TECH3 = t3vf_", the.datafile.io.3step,
        sep="\n")  
      
      the.io.name.v.frat<-paste("C:/Users/vcole/Desktop/aim2/",all.sets[[i]][j],"/",all.sets[[i]][j],"_io_r",r,"_v_frat.inp",sep="")
      the.io.input.v.frat<-file(the.io.name.v.frat)
      writeLines(the.io.text.v.frat, the.io.input.v.frat)
      close(the.io.input.v.frat)
      runModels(the.io.name.v.frat,replaceOutfile="never")
    }
  }
}
